using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MovimientoCruceta : MonoBehaviour
{
    public float velocidadMovimientoCruceta = 15f; 
    public Vector2 limitesY = new Vector2(3.5f, 9f); // L칤mites para el eje Y
    public Vector2 limitesZ = new Vector2(-7.5f, 7.5f); // L칤mites para el eje Z

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        float horizontal = Input.GetAxis("Horizontal"); // A D 游 游목
        float vertical = Input.GetAxis("Vertical");     // W S 游모 游몪

        // Calcula y aplica movimiento en Y y Z
        Vector3 movement = new Vector3(0, vertical, horizontal) * velocidadMovimientoCruceta * Time.deltaTime;
        transform.position += movement;

        // Limita la posici칩n de la cruceta (a partir de las variables inicializadas al principio)
        float clampedY = Mathf.Clamp(transform.position.y, limitesY.x, limitesY.y);
        float clampedZ = Mathf.Clamp(transform.position.z, limitesZ.x, limitesZ.y); 

        // Actualiza la posici칩n con los l칤mites
        transform.position = new Vector3(transform.position.x, clampedY, clampedZ);
    }
}
